package com.example.rossen.androidadvancedlearning.libraries

enum class Emoji {
    LEFT_OPEN_RIGHT_CLOSED_SMILING,
    LEFT_OPEN_RIGHT_CLOSED_FROWNING,
    LEFT_OPEN_RIGHT_OPEN_SMILING,
    LEFT_OPEN_RIGHT_OPEN_FROWNING,
    LEFT_CLOSED_RIGHT_CLOSED_SMILING,
    LEFT_CLOSED_RIGHT_CLOSED_FROWNING,
    LEFT_CLOSED_RIGHT_OPEN_SMILING,
    LEFT_CLOSED_RIGHT_OPEN_FROWNING,
}